// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqwvtbayvbsxvryniquv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxd3Z0YmF5dmJzeHZyeW5pcXV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYyNDU5NzUsImV4cCI6MjA4MTgyMTk3NX0.6X_NjCD9e4AVioM7271yCZb90DRBK6-XdVI_XIZgnMA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});